import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../../../config/styles';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.COLOR_GREY_BACKGROUND,
  },
  currentCategory: {
    fontSize: 26,
    lineHeight: 29,
    color: COLORS.COLOR_LABEL,
    fontFamily: FONTS.FONT_EXTRA_BOLD,
    marginHorizontal: 6,
  },
  category: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    color: COLORS.COLOR_LABEL,
    marginHorizontal: 6,
  },
  container: {
    flex: 1,
    marginTop: 10,
  },
  feed: {
    width: 15,
    height: 19,
    marginLeft: 35,
  },
  storyImage: {
    width: 141,
    height: 79,
    borderRadius: 5,
  },
  story: {
    marginHorizontal: 10,
  },
  storyAvatarContainer: {
    width: 35,
    height: 35,
    backgroundColor: 'white',
    borderRadius: 33,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.COLOR_PRIMARY,
  },
  storyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 28,

    padding: 5,
  },
  storyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 7,
  },
  storyName: {
    fontSize: 10,
    lineHeight: 13,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    color: COLORS.COLOR_PRIMARY,
    marginLeft: 5,
  },
  storyStatus: {
    position: 'absolute',
    right: 5,
    top: 5,
    textTransform: 'capitalize',
    padding: 3,
    color: 'white',
    fontFamily: FONTS.FONT_REGULAR,
    fontSize: 5,
    width: 21,
    textAlign: 'center',
  },
  postAvatar: {
    height: 36,
    width: 36,
    borderRadius: 30,
  },
  postView: {
    flex: 1,
    alignItems: 'center',
    marginTop: 20,
  },
  postContainer: {
    height: 335,
    backgroundColor: 'white',
    padding: 20,
    width: '95%',
    borderRadius: 40,
    marginVertical: 5,
    alignSelf: 'center',
  },
  username: {
    fontSize: 16,
    lineHeight: 18,
    fontFamily: FONTS.FONT_BOLD,
  },
  date: {
    fontSize: 12,
    fontFamily: FONTS.FONT_REGULAR,
    color: '#352641',
  },
  postDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  details: {
    marginLeft: 20,
  },
  imagePost: {
    height: 205,
    backgroundColor: COLORS.COLOR_POST_BACKGROUND,
    borderRadius: 20,
  },
  postImage: {
    height: '75%',
    width: '95%',
    alignSelf: 'center',
  },
  smallCaption: {
    fontSize: 10,
    lineHeight: 13,
    color: COLORS.COLOR_PRIMARY,
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  smallGrey: {
    top: -0,
    color: '#9b9b9b',
    fontSize: 10,
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  controls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  leftControl: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rightControl: {
    flex: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  comments: {
    fontSize: 12,
    fontFamily: FONTS.FONT_BOLD,
    color: COLORS.COLOR_SECONDARY_LABEL,
  },
  controlIcons: {
    marginLeft: 5,
  },
  repost: {
    fontSize: 13,
    lineHeight: 15,
    fontFamily: FONTS.FONT_REGULAR,
    color: COLORS.COLOR_SECONDARY_LABEL,
    marginTop: 10,
    marginBottom: 5,
    marginLeft: 15,
  },
  caption: {
    fontSize: 14,
    lineHeight: 15,
    fontFamily: FONTS.FONT_REGULAR,
    marginLeft: 15,
    marginTop: 10,
    color: COLORS.COLOR_SECONDARY_LABEL,
  },
  videoPost: {
    marginTop: 10,
    height: 120,
    backgroundColor: COLORS.COLOR_POST_BACKGROUND,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    marginHorizontal: 10,
  },
  videoImage: {
    width: '30%',
    height: '100%',
  },
  playIcon: {
    position: 'absolute',
    top: '22%',
    left: '6%',
  },
  eventContainer: {
    height: 336,
    backgroundColor: 'white',
    padding: 10,
    paddingHorizontal: 15,
    width: '95%',
    borderRadius: 40,
    marginVertical: 5,
    alignSelf: 'center',
  },
  logo: {
    width: 48,
    height: 37,
  },
  outerRow: {
    justifyContent: 'space-between',
  },
  popularText: {
    fontSize: 16,
    lineHeight: 18,
    fontFamily: FONTS.FONT_EXTRA_BOLD,
  },
  seeText: {
    fontFamily: FONTS.FONT_SEMI_BOLD,
    color: COLORS.COLOR_LABEL,
  },
  boximageContainer: {
    marginTop: 15,
    alignSelf: 'center',
    margin: 0,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotStyle: {
    width: 7,
    height: 7,
    borderRadius: 5,
    backgroundColor: COLORS.COLOR_PRIMARY,
  },
  image: {
    height: '88%',
    width: 321,
    borderRadius: 28,
    marginRight: 30,
    marginLeft: 10,
  },
  customSlide: {
    margin: 0,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionsCard: {
    backgroundColor: COLORS.COLOR_PRIMARY,
    width: 74,
    height: 40,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 25,
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 5,
  },
  songsDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 10,
  },
  rightView: {
    marginLeft: 15,
  },
  song: {
    fontSize: 14,
    color: '#999999',
    fontFamily: FONTS.FONT_REGULAR,
  },
  artist: {
    fontSize: 16,
    color: '#484d54',
    fontFamily: FONTS.FONT_BOLD,
  },
  recordings: {
    fontSize: 14,
    color: '#484d54',
    fontFamily: FONTS.FONT_REGULAR,
  },
  songTitle: {
    fontFamily: FONTS.FONT_SEMI_BOLD,
    fontSize: 16,
  },
  seeAll: {
    color: COLORS.COLOR_DARK_PURPLE,
    fontFamily: FONTS.FONT_REGULAR,
    fontSize: 15,
  },
  row: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  categoryText: {
    color: 'white',
    fontSize: 8,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
});
