//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';
export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';
export const FORGOT_PASSWORD_ENABLE_LOADER = 'FORGOT_PASSWORD_ENABLE_LOADER';
export const FORGOT_PASSWORD_DISABLE_LOADER = 'FORGOT_PASSWORD_DISABLE_LOADER';
export const NEW_PASSWORD_ENABLE_LOADER = 'NEW_PASSWORD_ENABLE_LOADER';
export const NEW_PASSWORD_DISABLE_LOADER = 'NEW_PASSWORD_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const CLEAR_LOGIN_MESSAGE = 'CLEAR_LOGIN_MESSAGE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_RESPONSE = 'FORGOT_PASSWORD_RESPONSE';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST';
export const NEW_PASSWORD_RESPONSE = 'NEW_PASSWORD_RESPONSE';
export const NEW_PASSWORD_FAILED = 'NEW_PASSWORD_FAILED';
