/* App config for images
 */

export const ICONS = {
  startedIcon: require('../assets/images/startedIcon.png'),
  logo: require('../assets/images/icon.png'),
  song: require('../assets/images/songicon.png'),
  feed: require('../assets/images/feed.png'),
  feedblack: require('../assets/images/feedblack.png'),
  users: require('../assets/images/users.png'),
  task: require('../assets/images/task.png'),
  draweruser: require('../assets/images/draweruser.png'),
  hindi: require('../assets/images/languages/hindi.png'),
  jam: require('../assets/images/jam.png'),
  youtube: require('../assets/images/youtube.png'),
  music: require('../assets/images/music.png'),
  playblack: require('../assets/images/playblack.png'),
};
export const IMAGES = {
  welcome: require('../assets/images/welcome.png'),
  bg_light: require('../assets/images/bglight.png'),
  startedCard: require('../assets/images/startedCard.png'),
  recommended: require('../assets/images/recemmondations.png'),
  rankingOne: require('../assets/images/ranking1.png'),
  rankingTwo: require('../assets/images/ranking2.png'),
  rankignThree: require('../assets/images/ranking3.png'),
  rankingUser: require('../assets/images/rankinguser.png'),
  event: require('../assets/images/events.png'),
  userTwo: require('../assets/images/user2.png'),
  userpic: require('../assets/images/userpic.png'),
  useravatar: require('../assets/images/avatar.png'),
  post: require('../assets/images/post.png'),
  story1: require('../assets/images/story1.png'),
  story2: require('../assets/images/story2.png'),
  story3: require('../assets/images/story3.png'),
  ipost: require('../assets/images/ipost.png'),
  drawerheader: require('../assets/images/drawerheader.png'),
  splashlogo: require('../assets/images/splashlogo.png'),
  circlecard: require('../assets/images/circlecard.png'),
  firstrow: require('../assets/images/firstrow.png'),
  secondrow: require('../assets/images/secondrow.png'),
  thirdrow: require('../assets/images/thirdrow.png'),
  locationbg: require('../assets/images/locationbg.png'),
  profileTab: require('../assets/images/profiletab.png'),
  recentPicOne: require('../assets/images/recentpic1.png'),
  recentPicTwo: require('../assets/images/recentpic2.png'),
  recentPicThree: require('../assets/images/recentpic3.png'),
};
