import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../../config/styles';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.COLOR_GREY_BACKGROUND,
  },
  currentCategory: {
    fontSize: 26,
    lineHeight: 29,
    color: COLORS.COLOR_LABEL,
    fontFamily: FONTS.FONT_EXTRA_BOLD,
    marginHorizontal: 6,
  },
  category: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    color: COLORS.COLOR_LABEL,
    marginHorizontal: 6,
  },
  container: {
    flex: 1,
    marginTop: 10,
  },
  feed: {
    width: 15,
    height: 19,
    marginRight: 10,
  },
  storyImage: {
    width: 141,
    height: 79,
    borderRadius: 5,
  },
  story: {
    marginHorizontal: 10,
  },
  storyAvatarContainer: {
    width: 35,
    height: 35,
    backgroundColor: 'white',
    borderRadius: 33,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.COLOR_PRIMARY,
  },
  storyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 28,

    padding: 5,
  },
  storyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 7,
  },
  storyName: {
    fontSize: 10,
    lineHeight: 13,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    color: COLORS.COLOR_PRIMARY,
    marginLeft: 5,
  },
  storyStatus: {
    position: 'absolute',
    right: 5,
    top: 5,
    textTransform: 'capitalize',
    padding: 3,
    color: 'white',
    fontFamily: FONTS.FONT_REGULAR,
    fontSize: 5,
    width: 21,
    textAlign: 'center',
  },
  postAvatar: {
    height: 36,
    width: 36,
    borderRadius: 30,
  },
  postView: {
    flex: 1,
    alignItems: 'center',
    marginTop: 20,
  },
  postContainer: {
    height: 335,
    backgroundColor: 'white',
    padding: 20,
    width: '95%',
    borderRadius: 40,
    marginVertical: 5,
  },
  username: {
    fontSize: 16,
    lineHeight: 18,
    fontFamily: FONTS.FONT_BOLD,
  },
  date: {
    fontSize: 12,
    fontFamily: FONTS.FONT_REGULAR,
    color: '#352641',
  },
  postDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  details: {
    marginLeft: 20,
  },
  imagePost: {
    height: 205,
    backgroundColor: COLORS.COLOR_POST_BACKGROUND,
    borderRadius: 20,
  },
  postImage: {
    height: '75%',
    width: '95%',
    alignSelf: 'center',
  },
  smallCaption: {
    fontSize: 10,
    lineHeight: 13,
    color: COLORS.COLOR_PRIMARY,
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  smallGrey: {
    top: -0,
    color: '#9b9b9b',
    fontSize: 10,
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  controls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  leftControl: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rightControl: {
    flex: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  comments: {
    fontSize: 12,
    fontFamily: FONTS.FONT_BOLD,
    color: COLORS.COLOR_SECONDARY_LABEL,
  },
  controlIcons: {
    marginLeft: 5,
  },
  repost: {
    fontSize: 13,
    lineHeight: 15,
    fontFamily: FONTS.FONT_REGULAR,
    color: COLORS.COLOR_SECONDARY_LABEL,
    marginTop: 10,
    marginBottom: 5,
    marginLeft: 15,
  },
  caption: {
    fontSize: 14,
    lineHeight: 15,
    fontFamily: FONTS.FONT_REGULAR,
    marginLeft: 15,
    marginTop: 10,
    color: COLORS.COLOR_SECONDARY_LABEL,
  },
  videoPost: {
    marginTop: 10,
    height: 120,
    backgroundColor: COLORS.COLOR_POST_BACKGROUND,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    marginHorizontal: 10,
  },
  videoImage: {
    width: '30%',
    height: '80%',
  },
  playIcon: {
    position: 'absolute',
    top: '22%',
    left: '6%',
  },
  labelContainer: {
    height: 60,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  labelView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionBtnContainer: {
    position: 'absolute',
    top: 10,
    right: 30,
    zIndex: 100,
  },
  addBtn: {
    width: 39,
    height: 39,
    borderRadius: 39,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,

    elevation: 11,
  },

  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 5,
    marginHorizontal: 15,
  },
  simplerow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  showActionsContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    // opacity: 0.5,
    zIndex: 100,
  },
  optionsContainer: {
    top: '10%',
    alignItems: 'flex-end',
    marginRight: 20,
  },
  leftOption: {
    width: 169,
    height: 62,
    borderRadius: 41,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  optionText: {
    fontSize: 25,
    color: 'white',
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  optionIcon: {
    width: 62,
    height: 62,
    borderRadius: 62,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  optionImage: {
    height: 22,
    width: 22,
  },
  loginModal: {
    position: 'absolute',
    height: 250,
    width: '100%',
    top: '28%',
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    borderWidth: 0,
    margin: 0,
    padding: 0,
  },
  linearGradient: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  actionsContainer: {
    flexDirection: 'row',
    bottom: -20,
    justifyContent: 'space-between',
    paddingHorizontal: 50,
  },
  actions: {},
  actionBtn: {
    backgroundColor: COLORS.COLOR_PRIMARY,
    height: 30,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 25,
    borderWidth: 0,
    padding: 20,
  },
  actionTitle: {
    color: 'white',
    fontSize: 14,
    fontFamily: FONTS.FONT_BOLD,
    textTransform: 'uppercase',
  },
  social: {
    borderRadius: 22,
    height: 50,
    width: 50,
    borderWidth: 0,
  },
  loginText: {
    fontSize: 18,
    lineHeight: 23,
    fontFamily: FONTS.FONT_BOLD,
  },
  account: {
    color: 'white',
    fontFamily: FONTS.FONT_REGULAR,
  },
  signup: {
    color: 'black',
    fontFamily: FONTS.FONT_REGULAR,
  },
  contact: {
    color: 'white',
    position: 'absolute',
    bottom: 10,
    right: 15,
  },
  sheetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
