import { StyleSheet } from 'react-native';
import { FONTS, COLORS } from '../../../config/styles';

export default StyleSheet.create({
  screen: { flex: 1 },
  menuItem: {
    marginHorizontal: 5,
  },
  currentMenu: {
    fontSize: 24,
    fontFamily: FONTS.FONT_BOLD,
  },
  menu: {
    fontSize: 16,
    fontFamily: FONTS.FONT_REGULAR,
  },
  header: {
    marginTop: 10,
    padding: 5,
    paddingHorizontal: 10,
  },
  menuList: {
    alignItems: 'center',
    flexGrow: 1,
  },

  inputContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    backgroundColor: COLORS.COLOR_WHITE,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    height: 50,
    borderRadius: 36,
    paddingHorizontal: 10,
    marginRight: '20%',
    marginBottom: 15,
    marginLeft: 10,
  },
  input: {
    flex: 1,
  },
  container: {
    marginTop: 10,
  },
  categoryCard: {
    height: 130,
    width: 120,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    margin: 6,
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    borderRadius: 15,
    justifyContent: 'flex-end',
    marginBottom: 5,
  },
  categoryText: {
    color: 'black',
    fontFamily: FONTS.FONT_SEMI_BOLD,
    textTransform: 'uppercase',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 13,
    marginHorizontal: 8,
  },

  currentCategory: {
    color: 'white',
    backgroundColor: COLORS.COLOR_PRIMARY,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    textTransform: 'uppercase',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 13,
    padding: 10,
    borderRadius: 40,
    marginHorizontal: 8,
  },
  categoryContainer: {
    alignItems: 'center',
    flex: 1,
  },
  video: {
    right: 20,
    flex: 1,
  },
  column: {
    backgroundColor: 'white',
    paddingBottom: 10,
    marginTop: 10,
    flex: 1,
  },
  listView: {
    backgroundColor: 'white',
    height: 260,
  },
  card: {
    width: 120,
    overflow: 'hidden',
    padding: 0,
    borderWidth: 0,
    elevation: 0,
    paddingTop: 0,
    marginHorizontal: 5,
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  name: {
    fontSize: 14,
    lineHeight: 18,
    marginTop: 10,
    fontFamily: FONTS.FONT_REGULAR,
    color: '#999999',
  },
  views: {
    fontFamily: FONTS.FONT_BOLD,
  },
  likesView: {
    marginRight: 10,
    marginBottom: 20,
    flexDirection: 'row',
  },
  imageContainer: {
    width: '100%',
    height: '70%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  count: {
    color: 'white',
    fontFamily: FONTS.FONT_BOLD,
    marginLeft: 5,
    fontSize: 10,
  },
  outerrow: {
    flexDirection: 'row',
    marginTop: 2,
  },
  row: {
    marginLeft: 5,
    flexDirection: 'row',
  },
  subtitle: {
    fontSize: 13,
    color: '#999999',
    fontFamily: FONTS.FONT_REGULAR,
  },
  largeImage: {
    height: 270,
    width: 240,
    marginHorizontal: 10,
  },
  title: {
    fontSize: 18,
    lineHeight: 19,
    color: '#999999',
    marginTop: 10,
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  label: {
    color: COLORS.COLOR_PRIMARY,
    marginLeft: 10,
    fontSize: 14,
    fontFamily: FONTS.FONT_SEMI_BOLD,
    marginBottom: 5,
    marginTop: 10,
  },
  boximageContainer: {
    height: 150,
  },
  dotStyle: {
    width: 7,
    height: 7,
    borderRadius: 5,
    backgroundColor: COLORS.COLOR_PRIMARY,
  },
  sliderBox: {
    height: 200,
    backgroundColor: COLORS.COLOR_PRIMARY,
  },
  boxContainer: {
    paddingVertical: 10,
    backgroundColor: COLORS.COLOR_PRIMARY_LIGHT,
    borderRadius: 20,
    height: 200,
    borderWidth: 1,
    borderColor: '#707070',
  },
  topFollowingCard: {
    padding: 10,
    backgroundColor: 'white',
    flex: 0.5,
  },
  followingHeader: {
    fontSize: 15,
    marginTop: 10,
    fontFamily: FONTS.FONT_SEMI_BOLD,
  },
  followingSubtitle: {
    color: COLORS.COLOR_GREY_TRANSP,
    marginTop: 20,
    textAlign: 'center',
    fontFamily: FONTS.FONT_REGULAR,
  },
  followingContainer: {
    flex: 1,
    backgroundColor: '#e0e0e0',
  },
  blackLabel: {
    color: COLORS.COLOR_BLACK,
    marginLeft: 10,
    fontSize: 14,
    fontFamily: FONTS.FONT_BOLD,
    marginBottom: 5,
    marginTop: 10,
  },
  eventImage: {
    marginTop: '5%',
    height: '70%',
    width: '70%',
    alignSelf: 'center',
    marginRight: 25,
  },
  eventContainer: {
    backgroundColor: COLORS.COLOR_PRIMARY_LIGHT,
    height: 197,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 21,
    marginHorizontal: 5,
  },
});
