export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const ENABLE_SEARCH_LOADER = 'ENABLE_SEARCH_LOADER';
export const DISABLE_SEARCH_LOADER = 'DISABLE_SEARCH_LOADER';
