export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const ENABLE_GET_USERS_LOADER = 'ENABLE_GET_USERS_LOADER';
export const DISABLE_GET_USERS_LOADER = 'DISABLE_GET_USERS_LOADER';

export const GET_FOLLOWERS_REQUEST = 'GET_FOLLOWERS_REQUEST';
export const GET_FOLLOWERS_RESPONSE = 'GET_FOLLOWERS_RESPONSE';
export const GET_FOLLOWERS_FAILED = 'GET_FOLLOWERS_FAILED';

export const GET_FOLLOWING_REQUEST = 'GET_FOLLOWING_REQUEST';
export const GET_FOLLOWING_RESPONSE = 'GET_FOLLOWING_RESPONSE';
export const GET_FOLLOWING_FAILED = 'GET_FOLLOWING_FAILED';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_RESPONSE = 'FOLLOW_USER_RESPONSE';
export const FOLLOW_USER_FAILED = 'FOLLOW_USER_FAILED';

export const GET_USERS_PROFILE_REQUEST = 'GET_USERS_PROFILE_REQUEST';
export const GET_USERS_PROFILE_RESPONSE = 'GET_USERS_PROFILE_RESPONSE';
export const GET_USERS_PROFILE_FAILED = 'GET_USERS_PROFILE_FAILED';
